# Generated by Django 2.1.1 on 2019-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_user',
            name='stu_no',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='record_visitor',
            name='visitor_name',
            field=models.CharField(max_length=128),
        ),
    ]
